---
- hosts: all
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache: yes

  - name: base packages
    package:
      name:
        - git
        - htop
        - python3
        - screen
        - tmux
      state: present
