---
# all:
#   hosts:
#   children:
#     new:
#       hosts:
#         raspberrypi.local:
#     raspberrypi:
#       hosts:
#       children:
#         ansibles:
#           hosts:
#             ansible.local:
#         jenkins:
#           hosts:
#             ansible.local:
#         mts:
#           hosts:
#             mts.local:
#         piholes:
#           hosts:
#             pihole.local:
#         speakers:
#           hosts:
#             kitchenspeakers.local:
#
all:
  children:
    new:
      hosts:
        raspberrypi.local: {}
    raspberrypi:
      children:
        ansibles:
          hosts:
            ansible.local: {}
        jenkins:
          hosts:
            ansible.local: {}
        mts:
          hosts:
            mts.local: {}
        piholes:
          hosts:
            pihole.local: {}
        speakers:
          hosts:
            kitchenspeakers.local: {}
    ungrouped: {}
