---
all:
  hosts:
  children:
    raspberrypi:
      hosts:
      children:
        ansibles:
          hosts:
            ansible.local:
        piholes:
          hosts:
            pihole.local:
        speakers:
          hosts:
            kitchenspeakers.local:
        jenkins:
          hosts:
            jenkins.local:
        new:
          hosts:
            raspberrypi.local:
