---
all:
  hosts:
  children:
    ansibles:
      hosts:
        ansible.local:
    piholes:
      hosts:
        pihole.local:
    raspberrypi:
      hosts:
        ansible.local:
        kitchenspeakers.local:
        pihole.local:
        raspberrypi.local:
    speakers:
      hosts:
        kitchenspeakers.local:
