---
all:
  hosts:
  children:
    new:
      hosts:
        raspberrypi.local:
    raspberrypi:
      hosts:
      children:
        ansibles:
          hosts:
            ansible.local:
        piholes:
          hosts:
            pihole.local:
        speakers:
          hosts:
            kitchenspeakers.local:
