---
- hosts: jenkins
  become: true

  vars:
#    jenkins_hostname: jenkins.local
    java_packages:
      - openjdk-11-jre
    jenkins_plugins:
      - ansible
      - ant
      - antisamy-markup-formatter
      - blueocean
      - build-timeout
      - credentials-binding
      - email-ext
      - git
      - github-branch-source
      - gradle
      - ldap
      - mailer
      - matrix-auth
      - pam-auth
      - pipeline-github-lib
      - pipeline-stage-view
      - ssh-slaves
      - workflow-aggregator
      - ws-cleanup

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
