---
- hosts: jenkins
  become: true

  vars:
    jenkins_hostname: jenkins.local
    java_packages:
      - openjdk-11-jre
    jenkins_plugins:
      - ansible
      - blueocean
      - workflow-aggregator
      - git
      - pam-auth
      - antisamy-markup-formatter
      - ant
      - ws-cleanup
      - github-branch-source
      - ldap
      - build-timeout
      - pipeline-github-lib
      - ssh-slaves
      - email-ext
      - credentials-binding
      - gradle
      - pipeline-stage-view
      - matrix-auth
      - mailer

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
