---
# tasks file for colinj.shaiport-sync
- name: install requirements for shairport-sync
  become: yes
  package:
    name:
      - autoconf
      - automake
      - avahi-daemon
      - build-essential
      - git
      - libasound2-dev
      - libavahi-client-dev
      - libconfig-dev
      - libdaemon-dev
      - libpopt-dev
      - libssl-dev
      - libtool
      - xmltoman
    state: present

# tasks to build and install shairport-sync
- name: git clone shairport-sync
  git:
    repo: https://github.com/mikebrady/shairport-sync.git
    dest: /home/pi/shairport-sync

- name: run autoreconf
  command: /usr/bin/autoreconf -i -f
  args:
    chdir: /home/pi/shairport-sync

- name: run ./configure
  command:
  args:
    chdir: /home/pi/shairport-sync
    argv:
      - ./configure
      - --sysconfdir=/etc
      - --with-alsa
      - --with-avahi
      - --with-ssl=openssl
      - --with-systemd

- name: build shairport-sync
  community.general.make:
    chdir: /home/pi/shairport-sync

- name: install shairport-sync
  community.general.make:
    chdir: /home/pi/shairport-sync
    target: install

- name: enable and (re)start shairport-sync service
  service:
    name: shairport-sync
    enabled: yes
    state: restarted
