---
# tasks file for raspberrypi
- name: 'full-upgrade'
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: full

- name: 'install base packages'
  package:
    name:
      - facter
      - git
      - htop
      - python3
      - python3-dev
      - ruby
      - screen
      - tmux
    state: present
