---
# tasks file for raspberrypi
  tasks:

  - name: update apt
    apt:
      update_cache: yes

  - name: full-upgrade
    apt:
      autoclean: yes
      autoremove: yes
      update_cache: yes
      upgrade: full

  - name: install base packages
    package:
      name:
        - git
        - htop
        - python3
        - screen
        - tmux
      state: present
