---
# tasks file for raspberrypi
- name: full-upgrade
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: full

- name: install base packages
  package:
    name:
      - git
      - htop
      - python3
      - python3-dev
      - screen
      - tmux
    state: present
