---
# tasks file for raspberrypi
- name: 'install base packages'
  package:
    name:
      - facter
      - git
      - golang
      - htop
      - python3
      - python3-dev
      - python3-pip
      - ruby
      - screen
      - tmux
    state: present
