---
# tasks file for colinj.shaiport-sync
- name: 'install requirements for shairportsync'
  become: yes
  package:
    name:
      - autoconf
      - automake
      - avahi-daemon
      - build-essential
      - git
      - libasound2-dev
      - libavahi-client-dev
      - libconfig-dev
      - libdaemon-dev
      - libpopt-dev
      - libssl-dev
      - libtool
      - xmltoman
    state: present
